name: Update GitHub Project with my assigned issues & PRs

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:      # Allow manual triggers

jobs:
  sync-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Sync assigned issues to project
        env:
          GITHUB_TOKEN: ${{ secrets.GH_CLASSIC_TOKEN }}
          PROJECT_NUMBER: "1"
          USERNAME: ${{ github.actor }}
        run: |
          # Get the last week's worth of issues
          week_ago=$(date -d "1 day ago" +%Y-%m-%d)

          # Get recently created OR assigned issues/PRs
          gh search issues \
            --include-prs \
            --assigned @me \
            --state open \
            --updated ">=$week_ago" \
            --json url \
          | jq -r '.[].url' \
          | while read -r url; do
            echo "Adding issue/PR $url to project"
            gh project item-add "$PROJECT_NUMBER" --owner "$USERNAME" --url "$url" || true
          done
