name: Update GitHub Project with my assigned issues & PRs

on:
  issues:
    types: [assigned]
  pull_request:
    types: [assigned]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add item to project
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          PROJECT_NUMBER: ${{ secrets.PROJECT_NUMBER }}
          ORG: ${{ secrets.OWNER }}
        run: |
          # Use PR URL if it's a PR event, otherwise use issue URL
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            URL="${{ github.event.pull_request.html_url }}"
          else
            URL="${{ github.event.issue.html_url }}"
          fi
          gh project item-add "$PROJECT_NUMBER" --owner "$ORG" --url "$URL"
